### ISSUE TITLE
Tracking: Support V3 Features

### ISSUE THREAD

**Issue by Fernthedev** [StackDoubleFlow/NoodleExtensions#49]
If anyone would like to contribute any of the NE v3 functionality, they are welcome to do.

- [x] Most key renames are already done (`_animate` -> `animate`)
- [x] Flip in V3
- [x] Arcs/Sliders support
  - [x] Animation
  - [x] Spawn JD etc. math
  - [x] Uncap height
- [x] Fake notes array
  - [x] Requires CJD rework to support loading NoteData/ObstacleData/SliderData from other entrypoints, most notably `customData.fakeNotes` and the arc/slider/obstacle variants
 
None of these features have been tested AT ALL in v3, therefore it is not considered to be "stable".
